baseURL: https://hofbaueroverview.netlify.app
languageCode: en-us
title: Patrick Hofbauer's Portfolio
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: A bit about me
    subtitle: |-
      I'm a student at LBS taking the Data Science for Business course with Professor Christodoulou. As part of this course, we are showcasing all the wonderful work we have worked on on our personal websites for you to look at and appreciate
    title: Hi, my name is Patrick 
  blog: {}
  contact:
    address:
      - city: Frankfurt, 60325
        country: Germany
        street: Savignystrasse 53
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: phofbauer.mfa2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +49 174 9653544
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Hofbauer Industries
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
      - icon: fa-instagram
        label: Patrick's Insta
        url: https://www.instagram.com/patrickhofbauer_/?hl=en
      - icon: fa-github
        label: Patrick's GitHub
        url: https://github.com/phofbauergit
      - icon: fa-linkedin
        label: Patrick's LinkedIn
        url: https://de.linkedin.com/in/patricktthofbauer
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum ############
 #     - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By yours truly, Patrick
    title: Snapshot
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: A little flasback
        title: My Time at LBS
        url: blogs/lbs_look
      - image: coding.jpg
        subtitle: A look at some of my work
        title: Data Science
        url: blogs/codework
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Get started with life? Maybe, but we'll never know"
    title: A new beginning
    url: blogs
    
    
